name: reviewdog
on: [pull_request]
jobs:

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'npm'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          eslint_flags: "src/**/*.ts"

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
